-- 记账本 3.1 多端合并与冲突备份
alter table public.ledger_states
  add column if not exists revision bigint not null default 0;

create table if not exists public.ledger_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null,
  revision bigint not null default 0,
  reason text not null default 'sync_conflict',
  conflict_count integer not null default 0 check (conflict_count >= 0),
  created_at timestamptz not null default now()
);

alter table public.ledger_backups enable row level security;

grant select, insert, delete on table public.ledger_backups to authenticated;
grant usage, select on sequence public.ledger_backups_id_seq to authenticated;

drop policy if exists "read own ledger backups" on public.ledger_backups;
create policy "read own ledger backups"
  on public.ledger_backups for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "create own ledger backups" on public.ledger_backups;
create policy "create own ledger backups"
  on public.ledger_backups for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "delete own ledger backups" on public.ledger_backups;
create policy "delete own ledger backups"
  on public.ledger_backups for delete to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists ledger_backups_user_created_idx
  on public.ledger_backups (user_id, created_at desc);
